version: '3'
volumes:
  nextcloud:
  db:
  reverse-proxy:

services:
  db:
    image: linuxserver/mariadb
    environment:
    - PUID=1000
    - PGID=1000
    - MYSQL_ROOT_PASSWORD=benoit45+
    - TZ=Europe/Paris
    - MYSQL_DATABASE=nextcloud #optional
    - MYSQL_USER=nextcloud #optional
    - MYSQL_PASSWORD=benoit45+ #optional
    volumes:
    - /srv/dev-disk-by-uuid-83c99957-a207-472a-a6ee-b5b1c81ef611/db:/var/lib/mysql
    restart: always
    labels:
    - traefik.enable=false
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/London
    - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    - USER=admin #optional
    - PASS=benoit45+ #optional
    volumes:
    - /srv/dev-disk-by-uuid-83c99957-a207-472a-a6ee-b5b1c81ef611/transmission/config/:/config
    - /srv/dev-disk-by-uuid-83c99957-a207-472a-a6ee-b5b1c81ef611/transmission/downloads:/downloads
    - /srv/dev-disk-by-uuid-83c99957-a207-472a-a6ee-b5b1c81ef611/transmission/watch:/watch
    - /srv/dev-disk-by-uuid-83c99957-a207-472a-a6ee-b5b1c81ef611/plex/animes:/animes
    ports:
    - 9091:9091
    - 51413:51413
    - 51413:51413/udp
    restart: unless-stopped
    labels:
    - "traefik.enable=true"
    - "traefik.http.services.torrent.loadbalancer.server.port=9091"
    - "traefik.http.routers.torrent.rule=Host(`torrent.chocot.be`)"
    - "traefik.http.routers.torrent.service=torrent"

  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    environment:
    - PUID=1000
    - PGID=1000
    - VERSION=docker
    - PLEX_CLAIM=claim-J5MDH9UhbyVrWEp8pCtB
    volumes:
    - /srv/dev-disk-by-uuid-83c99957-a207-472a-a6ee-b5b1c81ef611/plex/library:/config
    - /srv/dev-disk-by-uuid-83c99957-a207-472a-a6ee-b5b1c81ef611/plex/tvseries:/tv
    - /srv/dev-disk-by-uuid-83c99957-a207-472a-a6ee-b5b1c81ef611/plex/movies:/movies
    - /srv/dev-disk-by-uuid-83c99957-a207-472a-a6ee-b5b1c81ef611/plex/animes:/animes
    restart: unless-stopped
    labels:
    - "traefik.enable=true"
    - "traefik.http.services.video.loadbalancer.server.port=32400"
    - "traefik.http.routers.video.rule=Host(`video.chocot.be`)"
    - "traefik.http.routers.video.service=video"

  adminer:
    image: adminer:4.6.3-standalone
    labels:
    - traefik.enable=true
    - traefik.http.routers.adminer.rule=Host(`db.chocot.be`)
    - traefik.port=8080
    depends_on:
    - db

  app:
    image: nextcloud
    restart: always
    volumes:
    - /srv/dev-disk-by-uuid-83c99957-a207-472a-a6ee-b5b1c81ef611/nextcloud:/var/www/html
    environment:
    - MYSQL_PASSWORD=benoit45+
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    - MYSQL_HOST=db
    labels:
    - "traefik.enable=true"
    - "traefik.http.services.cloud.loadbalancer.server.port=80"
    - "traefik.http.routers.cloud.rule=Host(`cloud.chocot.be`)"
    - "traefik.http.routers.cloud.service=cloud"
    depends_on:
    - db

  calibre:
    image: linuxserver/calibre:arch
    container_name: calibre
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Paris
    - CLI_ARGS= #optional
    volumes:
    - /srv/dev-disk-by-uuid-83c99957-a207-472a-a6ee-b5b1c81ef611/calibre/config:/config
    ports:
    - 8080:8080
    - 8081:8081
    restart: unless-stopped
    labels:
    - "traefik.enable=true"
    - "traefik.http.services.book.loadbalancer.server.port=8080"
    - "traefik.http.routers.book.rule=Host(`book.chocot.be`)"
    - "traefik.http.routers.book.service=book"

  reverse-proxy:
    restart: always
    image: traefik:v2.0
    ports:
    - "443:443"
    - "80:80"
    volumes:
    - /srv/services.toml:/etc/traefik/services.toml
    - /srv/traefik.toml:/etc/traefik/traefik.toml
    - /var/run/docker.sock:/var/run/docker.sock
    labels:
    - "traefik.http.routers.api.rule=Host(`traefik.chocot.be`)"
    - "traefik.http.routers.api.service=api@internal"
    - "traefik.http.routers.api.entrypoints=http"
    - "traefik.http.routers.api.middlewares=auth"
    - "traefik.http.middlewares.auth.basicauth.users=pi:$$apr1$$5uYcSiA9$$pf3V/rEtqAG1I0ZLHRnT40"
    - "traefik.http.routers.nas.entrypoints=http"
    - "traefik.http.routers.nas.rule=Host(`omv.chocot.be`)"
    - "traefik.http.routers.nas.service=nas@file"
    - "traefik.http.routers.web.rule=Host(`chocot.be`)"
    - "traefik.http.routers.web.service=web@file"


