# Exemple de fichier avec Traefik d'implanté
volumes:
  reverse-proxy:

services:
    reverse-proxy:
    restart: always
    image: traefik:v2.0
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /mnt/usb/pi/services.toml:/etc/traefik/services.toml
      - /mnt/usb/pi/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.chocot.be`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=http"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=pi:$$apr1$$5uYcSiA9$$pf3V/rEtqAG1I0ZLHRnT40"

  apache:
    image: httpd:2.4
    container_name: apache
    restart: always
    volumes:
      - /mnt/usb/pi/apache:/usr/local/apache2/htdocs/
      - /mnt/usb/pi/apache-config/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - 8080:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.rule=Host(`chocot.be`)"
      - "traefik.http.routers.apache.entrypoints=http"
      - "traefik.http.services.apache.loadbalancer.server.port=80"
