version: '3'

volumes:
  nextcloud:
  db:
  reverse-proxy:

services:
  db:
    image: linuxserver/mariadb
    environment:
    - PUID=1000
    - PGID=1000
    - MYSQL_ROOT_PASSWORD=benoit45+
    - TZ=Europe/Paris
    - MYSQL_DATABASE=nextcloud #optional
    - MYSQL_USER=nextcloud #optional
    - MYSQL_PASSWORD=benoit45+ #optional
    volumes:
    - ./db:/var/lib/mysql
    restart: always
    labels:
    - traefik.enable=false

  adminer:
    image: adminer:4.6.3-standalone
    labels:
    - traefik.enable=true
    - traefik.http.routers.adminer.rule=Host(`db.chocot.be`)
    - traefik.port=8080
    depends_on:
    - db

  app:
    image: nextcloud
    restart: always
    volumes:
    - ./nextcloud:/var/www/html
    environment:
    - MYSQL_PASSWORD=benoit45+
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    - MYSQL_HOST=db
    labels:
    - "traefik.enable=true"
    - "traefik.http.services.cloud.loadbalancer.server.port=80"
    - "traefik.http.routers.cloud.entrypoints=http"
    - "traefik.http.routers.cloud.rule=Host(`cloud.chocot.be`)"
    - "traefik.http.routers.cloud.service=cloud"
    depends_on:
    - db

  reverse-proxy:
    restart: always
    image: traefik:v2.0
    ports:
    - "443:443"
    - "80:80"
    volumes:
    - /srv/services.toml:/etc/traefik/services.toml
    - /srv/traefik.toml:/etc/traefik/traefik.toml
    - /var/run/docker.sock:/var/run/docker.sock
    labels:
    - "traefik.http.routers.api.rule=Host(`traefik.chocot.be`)"
    - "traefik.http.routers.api.service=api@internal"
    - "traefik.http.routers.api.entrypoints=http"
    - "traefik.http.routers.api.middlewares=auth"
    - "traefik.http.middlewares.auth.basicauth.users=pi:$$apr1$$5uYcSiA9$$pf3V/rEtqAG1I0ZLHRnT40"
    - "traefik.http.routers.nas.entrypoints=http"
    - "traefik.http.routers.nas.rule=Host(`omv.chocot.be`)"
    - "traefik.http.routers.nas.service=nas@file"

