# Remplacer $SERVICES par le nom du service que vous voulez (ex : api, etc...) et l'ip du raspberry par son ip locale
[http]
  [http.services]
    [http.services.$SERVICES]
      [http.services.$SERVICES.loadBalancer]
        [[http.services.$SERVICES.loadBalancer.servers]]
          url = "http://IP_DU_RASPBERRY:PORT/"

    [http.services.$SERVICES]
      [http.services.$SERVICES.loadBalancer]
        [[http.services.angular.loadBalancer.servers]]
          url = "http://IP_DU_RASPBERRY:PORT"
