[http]
  [http.services]
    [http.services.symfony]
      [http.services.symfony.loadBalancer]
        [[http.services.symfony.loadBalancer.servers]]
          url = "http://192.168.1.16:81/"

    [http.services.angular]
      [http.services.angular.loadBalancer]
        [[http.services.angular.loadBalancer.servers]]
          url = "http://192.168.1.16:82/"